services:

  soniks-postgres:
    image: postgres:17.5
    container_name: soniks-postgres
    environment:
      POSTGRES_DB: $POSTGRES__DB
      POSTGRES_USER: $POSTGRES__USER
      POSTGRES_PASSWORD: $POSTGRES__PASSWORD
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - soniks_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES__USER} -d ${POSTGRES__DB}" ]
      interval: 5s
      timeout: 3s
      retries: 3

  soniks-backend:
    build: ../
    container_name: soniks-backend
    env_file: ../.env
    command: "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      soniks-postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ../src:/app/src

volumes:
  soniks_postgres_data:
